name: build

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.builder }}
    strategy:
      matrix:
        builder: [macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v1

    - run: |
        make -j8

    - uses: actions/upload-artifact@v2
      with:
        name: wrk-${{ matrix.job_name }}
        path: wrk
